connection: sqlite3
language: en
allow_reports: false
location: /var/lib/statping
sqlfile: /var/lib/statping/statping.db
disable_http: false
demo_mode: false
disable_logs: false
use_assets: false
sample_data: false
use_cdn: false
disable_colors: false
